### ISSUE TITLE
Need for M1 testing

### ISSUE THREAD

**Issue by philipturner** [LiarPrincess/Violet#12]
Your README says you don't have an M1 to test this on. Well, I do. Please let me know how I can help.

**Comment by LiarPrincess** [comment]
Ooo… thanks!

I will use `make` for all of the steps, if you do not want to use `make` then you can check our [Makefile](https://github.com/LiarPrincess/Violet/blob/main/Makefile) to see what command is really executed. For example `make build` translates to  `swift build`.

# Compile

```
# debug
make build

# release
make build-r:
```

There are differences between our debug and release builds, so it would be nice to try both.
Compilation may take a bit of time (few minutes).

On linux we get depreciated `Foundation.readdir_r` message, but it should not happen on macOS.

# Unit tests

```
make test
```

If something fails then please put the whole output in GitHub comment.

If things hang on `UnicodeDataDoesNotCrashTests.test_iterateAll` then this is expected, this test iterates all possible Unicode code points (2^21 values, that's a lot!).

# Python tests

```
# debug
make pytest

# release
make pytest-r
```

Expected output:
```
(things…)
=== Summary ===
🥰 All tests passed
⏱️ Running time: 99.78s
```

Again, separate release and debug. If something fails (there will be a message at the end) then please put the whole output in GitHub comment.

`RustPython - builtin_pow.py` may take a while, but this is expected (it will also take ~300mb of memory, but it will release it later).

Tbh. I am also curious how long it will take to execute them all on M1. On my machines:

|                         | debug  | release |
| ----------------------- | ------ | ------- |
| rMBP 2014 (lowest spec) | 104s   | 10.52s  |
| Ubuntu + Intel G4560    | 43.94s | 5.57s   |

# Other

You can also use Xcode:
- `make xcode` to make Xcode project
- open project
- select `PyTests` product
- build
- run unit tests (`cmd + u`)
- run (`cmd + r`)

Btw. If you don't have time to fix errors then this is ok. I may just spin EC2 with M1.

**Comment by philipturner** [comment]
I have an M1 Max with 10 CPU cores (8 performance, 2 efficiency). It also has 32 GB of LPDDR5 memory, with 6 times the bandwidth of M1. `builtin_pow.py` took 3 seconds under `pytest-r`.

[debug_build.txt](https://github.com/LiarPrincess/Violet/files/8566065/debug_build.txt)
[release_build.txt](https://github.com/LiarPrincess/Violet/files/8566066/release_build.txt)

**Comment by philipturner** [comment]
I don’t understand why the
post would be blocked. How long was it?

I prefer to make the PR myself.

**Comment by LiarPrincess** [comment]
Merged.

Thanks!
